package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carrito generated by hbm2java
 */
@Entity
@Table(name = "carrito", catalog = "marketplacebd")
public class Carrito implements java.io.Serializable {

	private int idcarrito;
	private Usuario usuario;
	private Set<CarritoProducto> carritoProductos = new HashSet<CarritoProducto>(0);

	public Carrito() {
	}

	public Carrito(int idcarrito) {
		this.idcarrito = idcarrito;
	}

	public Carrito(int idcarrito, Usuario usuario, Set<CarritoProducto> carritoProductos) {
		this.idcarrito = idcarrito;
		this.usuario = usuario;
		this.carritoProductos = carritoProductos;
	}

	@Id

	@Column(name = "idcarrito", unique = true, nullable = false)
	public int getIdcarrito() {
		return this.idcarrito;
	}

	public void setIdcarrito(int idcarrito) {
		this.idcarrito = idcarrito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrito")
	public Set<CarritoProducto> getCarritoProductos() {
		return this.carritoProductos;
	}

	public void setCarritoProductos(Set<CarritoProducto> carritoProductos) {
		this.carritoProductos = carritoProductos;
	}

}
