package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CuponDescuento generated by hbm2java
 */
@Entity
@Table(name = "cupon_descuento", catalog = "marketplacebd")
public class CuponDescuento implements java.io.Serializable {

	private int idcupon;
	private BigDecimal montoDescuento;
	private Set<Pago> pagos = new HashSet<Pago>(0);

	public CuponDescuento() {
	}

	public CuponDescuento(int idcupon, BigDecimal montoDescuento) {
		this.idcupon = idcupon;
		this.montoDescuento = montoDescuento;
	}

	public CuponDescuento(int idcupon, BigDecimal montoDescuento, Set<Pago> pagos) {
		this.idcupon = idcupon;
		this.montoDescuento = montoDescuento;
		this.pagos = pagos;
	}

	@Id

	@Column(name = "idcupon", unique = true, nullable = false)
	public int getIdcupon() {
		return this.idcupon;
	}

	public void setIdcupon(int idcupon) {
		this.idcupon = idcupon;
	}

	@Column(name = "monto_descuento", nullable = false, precision = 6)
	public BigDecimal getMontoDescuento() {
		return this.montoDescuento;
	}

	public void setMontoDescuento(BigDecimal montoDescuento) {
		this.montoDescuento = montoDescuento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuponDescuento")
	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

}
