  
package pe.edu.unsch.entities;
// Generated 19-nov-2020 22:02:54 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", catalog = "marketplacebd", uniqueConstraints = @UniqueConstraint(columnNames = "numero_ruc"))
public class Factura implements java.io.Serializable {

	private Integer idfactura;
	private Persona persona;
	private Date fecha;
	private float igv;
	private float subtotal;
	private String numeroRuc;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Factura() {
	}

	public Factura(Persona persona, Date fecha, float igv, float subtotal, String numeroRuc) {
		this.persona = persona;
		this.fecha = fecha;
		this.igv = igv;
		this.subtotal = subtotal;
		this.numeroRuc = numeroRuc;
	}

	public Factura(Persona persona, Date fecha, float igv, float subtotal, String numeroRuc, Set<Pedido> pedidos) {
		this.persona = persona;
		this.fecha = fecha;
		this.igv = igv;
		this.subtotal = subtotal;
		this.numeroRuc = numeroRuc;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfactura", unique = true, nullable = false)
	public Integer getIdfactura() {
		return this.idfactura;
	}

	public void setIdfactura(Integer idfactura) {
		this.idfactura = idfactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "igv", nullable = false, precision = 12, scale = 0)
	public float getIgv() {
		return this.igv;
	}

	public void setIgv(float igv) {
		this.igv = igv;
	}

	@Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
	public float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "numero_ruc", nullable = false, length = 11)
	public String getNumeroRuc() {
		return this.numeroRuc;
	}

	public void setNumeroRuc(String numeroRuc) {
		this.numeroRuc = numeroRuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factura")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}