package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * OfertaProducto generated by hbm2java
 */
@Entity
@Table(name = "oferta_producto", catalog = "marketplacebd")
public class OfertaProducto implements java.io.Serializable {

	private Long idofertaproducto;
	private Producto producto;
	private String descripcion;
	private Double precioOferta;
	
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date fechaInicio;
	
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date fechaLimite;
	
	private Boolean estado;

	public OfertaProducto() {
	}

	public OfertaProducto(Producto producto, String descripcion, Double precioOferta, Date fechaInicio,
			Date fechaLimite, Boolean estado) {
		this.producto = producto;
		this.descripcion = descripcion;
		this.precioOferta = precioOferta;
		this.fechaInicio = fechaInicio;
		this.fechaLimite = fechaLimite;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idofertaproducto", unique = true, nullable = false)
	public Long getIdofertaproducto() {
		return this.idofertaproducto;
	}

	public void setIdofertaproducto(Long idofertaproducto) {
		this.idofertaproducto = idofertaproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "precio_oferta", precision = 22, scale = 0)
	public Double getPrecioOferta() {
		return this.precioOferta;
	}

	public void setPrecioOferta(Double precioOferta) {
		this.precioOferta = precioOferta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_limite", length = 10)
	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
