package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductoDestacado generated by hbm2java
 */
@Entity
@Table(name = "producto_destacado", catalog = "marketplacebd")
public class ProductoDestacado implements java.io.Serializable {

	private int idproductodestacado;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public ProductoDestacado() {
	}

	public ProductoDestacado(int idproductodestacado) {
		this.idproductodestacado = idproductodestacado;
	}

	public ProductoDestacado(int idproductodestacado, Set<Producto> productos) {
		this.idproductodestacado = idproductodestacado;
		this.productos = productos;
	}

	@Id

	@Column(name = "idproductodestacado", unique = true, nullable = false)
	public int getIdproductodestacado() {
		return this.idproductodestacado;
	}

	public void setIdproductodestacado(int idproductodestacado) {
		this.idproductodestacado = idproductodestacado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productoDestacado")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
