package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regalo generated by hbm2java
 */
@Entity
@Table(name = "regalo", catalog = "marketplacebd")
public class Regalo implements java.io.Serializable {

	private int idregalo;
	private String descripcionRegalo;
	private String categoria;
	private String puntosRequeridos;
	private Set<CompradorFrecuente> compradorFrecuentes = new HashSet<CompradorFrecuente>(0);

	public Regalo() {
	}

	public Regalo(int idregalo, String descripcionRegalo, String categoria, String puntosRequeridos) {
		this.idregalo = idregalo;
		this.descripcionRegalo = descripcionRegalo;
		this.categoria = categoria;
		this.puntosRequeridos = puntosRequeridos;
	}

	public Regalo(int idregalo, String descripcionRegalo, String categoria, String puntosRequeridos,
			Set<CompradorFrecuente> compradorFrecuentes) {
		this.idregalo = idregalo;
		this.descripcionRegalo = descripcionRegalo;
		this.categoria = categoria;
		this.puntosRequeridos = puntosRequeridos;
		this.compradorFrecuentes = compradorFrecuentes;
	}

	@Id

	@Column(name = "idregalo", unique = true, nullable = false)
	public int getIdregalo() {
		return this.idregalo;
	}

	public void setIdregalo(int idregalo) {
		this.idregalo = idregalo;
	}

	@Column(name = "descripcion_regalo", nullable = false, length = 100)
	public String getDescripcionRegalo() {
		return this.descripcionRegalo;
	}

	public void setDescripcionRegalo(String descripcionRegalo) {
		this.descripcionRegalo = descripcionRegalo;
	}

	@Column(name = "categoria", nullable = false, length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "puntos_requeridos", nullable = false, length = 45)
	public String getPuntosRequeridos() {
		return this.puntosRequeridos;
	}

	public void setPuntosRequeridos(String puntosRequeridos) {
		this.puntosRequeridos = puntosRequeridos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regalo")
	public Set<CompradorFrecuente> getCompradorFrecuentes() {
		return this.compradorFrecuentes;
	}

	public void setCompradorFrecuentes(Set<CompradorFrecuente> compradorFrecuentes) {
		this.compradorFrecuentes = compradorFrecuentes;
	}

}
