package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "marketplacebd", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Rol implements java.io.Serializable {

	private int idrol;
	private String nombre;
	private Set<RolOpcion> rolOpcions = new HashSet<RolOpcion>(0);
	private Set<PersonaRol> personaRols = new HashSet<PersonaRol>(0);

	public Rol() {
	}

	public Rol(int idrol, String nombre) {
		this.idrol = idrol;
		this.nombre = nombre;
	}

	public Rol(int idrol, String nombre, Set<RolOpcion> rolOpcions, Set<PersonaRol> personaRols) {
		this.idrol = idrol;
		this.nombre = nombre;
		this.rolOpcions = rolOpcions;
		this.personaRols = personaRols;
	}

	@Id

	@Column(name = "idrol", unique = true, nullable = false)
	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolOpcion> getRolOpcions() {
		return this.rolOpcions;
	}

	public void setRolOpcions(Set<RolOpcion> rolOpcions) {
		this.rolOpcions = rolOpcions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<PersonaRol> getPersonaRols() {
		return this.personaRols;
	}

	public void setPersonaRols(Set<PersonaRol> personaRols) {
		this.personaRols = personaRols;
	}

}
