package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seguimiento generated by hbm2java
 */
@Entity
@Table(name = "seguimiento", catalog = "marketplacebd")
public class Seguimiento implements java.io.Serializable {

	private Long idSeguimiento;
	private String tipoSeguimiento;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Seguimiento() {
	}

	public Seguimiento(String tipoSeguimiento, Set<Pedido> pedidos) {
		this.tipoSeguimiento = tipoSeguimiento;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_seguimiento", unique = true, nullable = false)
	public Long getIdSeguimiento() {
		return this.idSeguimiento;
	}

	public void setIdSeguimiento(Long idSeguimiento) {
		this.idSeguimiento = idSeguimiento;
	}

	@Column(name = "tipo_seguimiento", length = 124)
	public String getTipoSeguimiento() {
		return this.tipoSeguimiento;
	}

	public void setTipoSeguimiento(String tipoSeguimiento) {
		this.tipoSeguimiento = tipoSeguimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seguimiento")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
