package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "tarjeta", catalog = "marketplacebd", uniqueConstraints = {
		@UniqueConstraint(columnNames = "cod_erificacion_tarjeta"), @UniqueConstraint(columnNames = "numero_tarjeta") })
public class Tarjeta implements java.io.Serializable {

	private int idtarjeta;
	private String numeroTarjeta;
	private String codErificacionTarjeta;
	private Date fechaDeposito;
	private BigDecimal montoDeposito;
	private Set<Pago> pagos = new HashSet<Pago>(0);

	public Tarjeta() {
	}

	public Tarjeta(int idtarjeta, String numeroTarjeta, String codErificacionTarjeta, Date fechaDeposito,
			BigDecimal montoDeposito) {
		this.idtarjeta = idtarjeta;
		this.numeroTarjeta = numeroTarjeta;
		this.codErificacionTarjeta = codErificacionTarjeta;
		this.fechaDeposito = fechaDeposito;
		this.montoDeposito = montoDeposito;
	}

	public Tarjeta(int idtarjeta, String numeroTarjeta, String codErificacionTarjeta, Date fechaDeposito,
			BigDecimal montoDeposito, Set<Pago> pagos) {
		this.idtarjeta = idtarjeta;
		this.numeroTarjeta = numeroTarjeta;
		this.codErificacionTarjeta = codErificacionTarjeta;
		this.fechaDeposito = fechaDeposito;
		this.montoDeposito = montoDeposito;
		this.pagos = pagos;
	}

	@Id

	@Column(name = "idtarjeta", unique = true, nullable = false)
	public int getIdtarjeta() {
		return this.idtarjeta;
	}

	public void setIdtarjeta(int idtarjeta) {
		this.idtarjeta = idtarjeta;
	}

	@Column(name = "numero_tarjeta", unique = true, nullable = false, length = 16)
	public String getNumeroTarjeta() {
		return this.numeroTarjeta;
	}

	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
	}

	@Column(name = "cod_erificacion_tarjeta", unique = true, nullable = false, length = 3)
	public String getCodErificacionTarjeta() {
		return this.codErificacionTarjeta;
	}

	public void setCodErificacionTarjeta(String codErificacionTarjeta) {
		this.codErificacionTarjeta = codErificacionTarjeta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_deposito", nullable = false, length = 19)
	public Date getFechaDeposito() {
		return this.fechaDeposito;
	}

	public void setFechaDeposito(Date fechaDeposito) {
		this.fechaDeposito = fechaDeposito;
	}

	@Column(name = "monto_deposito", nullable = false, precision = 10)
	public BigDecimal getMontoDeposito() {
		return this.montoDeposito;
	}

	public void setMontoDeposito(BigDecimal montoDeposito) {
		this.montoDeposito = montoDeposito;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

}
