package pe.edu.unsch.entities;
// Generated 26/11/2020 11:03:24 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "marketplacebd", uniqueConstraints = @UniqueConstraint(columnNames = "usuario"))
public class Usuario implements java.io.Serializable {

	private int idusuario;
	private CompradorFrecuente compradorFrecuente;
	private String usuario;
	private String contrasenia;
	private Date ultimoLogin;
	private Set<Comentario> comentarios = new HashSet<Comentario>(0);
	private Set<Carrito> carritos = new HashSet<Carrito>(0);
	private Set<Reclamo> reclamos = new HashSet<Reclamo>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Usuario() {
	}

	public Usuario(int idusuario, String usuario, String contrasenia) {
		this.idusuario = idusuario;
		this.usuario = usuario;
		this.contrasenia = contrasenia;
	}

	public Usuario(int idusuario, CompradorFrecuente compradorFrecuente, String usuario, String contrasenia,
			Date ultimoLogin, Set<Comentario> comentarios, Set<Carrito> carritos, Set<Reclamo> reclamos,
			Set<Persona> personas) {
		this.idusuario = idusuario;
		this.compradorFrecuente = compradorFrecuente;
		this.usuario = usuario;
		this.contrasenia = contrasenia;
		this.ultimoLogin = ultimoLogin;
		this.comentarios = comentarios;
		this.carritos = carritos;
		this.reclamos = reclamos;
		this.personas = personas;
	}

	@Id

	@Column(name = "idusuario", unique = true, nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompradorfrecuente")
	public CompradorFrecuente getCompradorFrecuente() {
		return this.compradorFrecuente;
	}

	public void setCompradorFrecuente(CompradorFrecuente compradorFrecuente) {
		this.compradorFrecuente = compradorFrecuente;
	}

	@Column(name = "usuario", unique = true, nullable = false, length = 90)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "contrasenia", nullable = false, length = 120)
	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultimo_login", length = 19)
	public Date getUltimoLogin() {
		return this.ultimoLogin;
	}

	public void setUltimoLogin(Date ultimoLogin) {
		this.ultimoLogin = ultimoLogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Comentario> getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(Set<Comentario> comentarios) {
		this.comentarios = comentarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Carrito> getCarritos() {
		return this.carritos;
	}

	public void setCarritos(Set<Carrito> carritos) {
		this.carritos = carritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Reclamo> getReclamos() {
		return this.reclamos;
	}

	public void setReclamos(Set<Reclamo> reclamos) {
		this.reclamos = reclamos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
